### ISSUE TITLE
数据库版粘液 方块数据重复

### ISSUE THREAD

**Issue by shixinzia** [SlimefunGuguProject/Netheopoiesis#17]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Netheopoiesis/issues)，且没有找到相同的问题

### 问题描述

玩家使用没任何问题
但是玩家在大规模培育过程中一个位置的方块有2个数据
会产生异常

### 复现步骤

1.大规模发展乌托邦
2.等待警告出现
3.警告会刷屏

### 预期行为

玩家使用正常且后台不会出现刷屏

### 服务器日志

无

### 错误报告

https://paste.guizhanss.net/zJrDs

### 服务端软件

Purpur

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun 230724-66e7391-Insider

### 插件版本

最新

**Comment by shixinzia** [comment]
补充，如果那个位置的方块挖掉，会重新出现一个:(且概率无掉落

**Comment by StarWishsama** [comment]
` * When trying to swap out a Slimefun Block in BlockStorage, the deletion will happen after a delay removing
 * the newly stored data. Not removing the old data will cause a duplicate block in storage reverting
 * to its previous state after a restart. This task will ensure the new block data is added only after the
 * removed block has left the deletion queue.`

又是老机制的问题 (?)

**Comment by shixinzia** [comment]
maybe
